### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by uesteibar** [retro-tool/retro-tool#15]
It'd great if we had some CI pipelines that would run our tests for the BE. There's a few options:

@atrzaska what do you think of using [CircleCI](https://circleci.com/)? I'm having a pretty good experience with it and they have a nice [free tier](https://circleci.com/pricing).

**Comment by atrzaska** [comment]
@uesteibar can you create a project in circleCI for this organization? I don't see this organization in cirlce CI after logging in.

**Comment by atrzaska** [comment]
Also, I will convert build process to use docker since now we have docker image of api.

**Comment by uesteibar** [comment]
I've added CircleCI permissions to this organization, you should be able to create a new project there.

Are you going to work on this @atrzaska? If that's the case please assign it to yourself and move it to the _In progress_ column 🚀

**Comment by atrzaska** [comment]
sure, I can work on this :rocket:

**Comment by uesteibar** [comment]
If https://github.com/retro-tool/retro-tool-api/pull/7 is merged before this one, it would be awesome if we could add `mix credo` and `mix compile --warnings-as-errors` to the CI as well.

**Comment by uesteibar** [comment]
now that we have dialyzer, we can also run `mix dialyzer` for type checking on CI
