### ISSUE TITLE
Improve voting

### ISSUE THREAD

**Issue by heliosam** [retro-tool/retro-tool#16]
### No design changes required:
- Hide other people's votes in voting phase:  seeing other team member's votes may bias your own votes
- Show to which cards I voted and how many times I did (only during voting phase): currently it is difficult to keep track how many times I voted. 
### May need design change
- Be able to undo a vote: maybe you change your mind and you want to put one of your votes in a different card: currently if you click on the one you just clicked, what happens is that you give an extra vote to it, all the contrary you were trying to do.

**Comment by uesteibar** [comment]
I see 3 different changes here, can we split that into 3 issues? This way we can work earlier on the ones that don't need design changes

**Comment by heliosam** [comment]
Splited into #17 #18 #19
