### ISSUE TITLE
Show to which cards I voted and how many times I did (only during voting phase)

### ISSUE THREAD

**Issue by heliosam** [retro-tool/retro-tool#18]
Currently it is difficult to keep track how many times I voted.

**Comment by uesteibar** [comment]
This will need design @iamsilesc

**Comment by uesteibar** [comment]
However, I'm thinking that, combined with https://github.com/retro-tool/retro-tool/issues/17, this wouldn't be needed right? because if you can only see your own votes during the voting phase, you already know what you voted and how many times.

**Comment by heliosam** [comment]
You are right 😅

**Comment by heliosam** [comment]
We can close this one @uesteibar
