### ISSUE TITLE
Link to next retro

### ISSUE THREAD

**Issue by rudeayelo** [retro-tool/retro-tool#2]
Show a link if nextRetroId exists, if not show a button to create a next retro.

**Comment by uesteibar** [comment]
@rudeayelo I understand this depends on https://github.com/retro-tool/retro-tool/issues/1, is that right?

**Comment by rudeayelo** [comment]
Yep

**Comment by uesteibar** [comment]
This is unblocked now as https://github.com/retro-tool/retro-tool/issues/1 has been resolved

**Comment by marciobarrios** [comment]
What's the use case? only when going to a finished retro that has a next retro associated?

**Comment by uesteibar** [comment]
@marciobarrios yes I understand so
