### ISSUE TITLE
Add  bugtracker

### ISSUE THREAD

**Issue by atrzaska** [retro-tool/retro-tool#22]
We're currently not notified about errors that happen in backend or frontend. To improve the reliability of retrotool we could add a bugtracker.

Some nice to have features of the bugtracker:

- notifications/alerts about bugs
- history of bugs
- details about each bug (user, browser, request, response, etc)
- elixir/javascript support
- free for open source

@retro-tool/all Any recommendations?

**Comment by uesteibar** [comment]
I did a quick research on the available free tiers:

- [Sentry](https://sentry.io/pricing/): 5k errors per month, one user
- [Rollbar](https://rollbar.com/pricing/): 5k errors per month, unlimited users
- [Bugsnag](https://www.bugsnag.com/pricing): 7.5k errors per month, unlimited users (I don't see any limit specified).

All of them have 30 days data retention, multi-language support, slack/email alerts.

I would go for either Rollbar or Bugsnag, I don't really mind. I hear good things from Rollback but I've never used it. Bugsnag worked just fine when we used it in the past right?

**Comment by rudeayelo** [comment]
I'd try Rollbar, what are side projects for?

**Comment by marciobarrios** [comment]
I don't really care, let's try Rollbar as Rude suugested.

**Comment by uesteibar** [comment]
Sounds good to me, moving this to ToDo 🚀

**Comment by uesteibar** [comment]
I've given rollbar a try and didn't manage to set it up properly with elixir. There's no official support, but there's [this library](https://github.com/ForzaElixir/rollbax). However, I didn't manage to make it work for automatically reporting all otp crashes.

Sentry [has official support](https://github.com/getsentry/sentry-elixir), and from what I could see in bugsnag I like it better too. The only downside is that it only allows one user so we'd need to share credentials. Are you fine with going with this?

**Comment by uesteibar** [comment]
BE done
