### ISSUE TITLE
Slack bot

### ISSUE THREAD

**Issue by uesteibar** [retro-tool/retro-tool#27]
I wanted to throw out some ideas for a slack bot:

- `/retrotool new` to create a new retro. It could use your workspace+channel names to make it fancy.
- If the retro is created from within the channel, then in that channel you can:
  - `/retrotool improve blablabla...` to add an item
  - `/retrotool action-items` to list action items

**Comment by marciobarrios** [comment]
I just read this, and I think it would be awesome, great idea!

**Comment by marciobarrios** [comment]
@retro-tool/all what do you think?

**Comment by rudeayelo** [comment]
Love the idea!

**Comment by uesteibar** [comment]
what do you think if we start with the following issues, in order of priority?

1. Create a new retro with `/retrotool new`
2. List action items for the last retro with `/retrotool actions`

And then we build up from there based on usage/feedback?

**Comment by uesteibar** [comment]
I've created https://github.com/retro-tool/retro-tool/issues/39, I'll close this issue and let's build up from there 💪
