### ISSUE TITLE
Disable ungroup in 'create actions' step

### ISSUE THREAD

**Issue by rudeayelo** [retro-tool/retro-tool#3]
Joined topics can be ungrouped in the create actions step, but can't be joined back. We should disable ungrouped at that point.

**Comment by uesteibar** [comment]
I just checked and this is already implemented in https://github.com/retro-tool/retro-tool-client/commit/b872a145bfda02076de2773eeb9050c56da6efbd, so I'll close this issue 👍 please do reopen it if anything is missing there
