### ISSUE TITLE
Add Open Graph metadata to improve link previews in Facebook or Twitter

### ISSUE THREAD

**Issue by marciobarrios** [retro-tool/retro-tool#35]
More info: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML

**Comment by uesteibar** [comment]
@marciobarrios what do you propose to add exactly?

**Comment by marciobarrios** [comment]
Something like this
```html
<meta property="og:image" content="https://developer.cdn.mozilla.net/static/img/opengraph-logo.dc4e08e2f6af.png">
<meta property="og:description" content="The Mozilla Developer Network (MDN) provides
information about Open Web technologies including HTML, CSS, and APIs for both Web sites
and HTML5 Apps. It also documents Mozilla products, like Firefox OS.">
<meta property="og:title" content="Mozilla Developer Network">
```

So every time the retro tool is shared (on Twitter, FB or any other website supporting this format) it will show something like this:

![CleanShot 2020-05-07 at 14 59 15](https://user-images.githubusercontent.com/47644/81297286-56325780-9073-11ea-9afa-58f6d34c4c8a.png)

**Comment by marciobarrios** [comment]
Related: https://joshwcomeau.com/snippets/html/html-skeleton

**Comment by marciobarrios** [comment]
Closed by https://github.com/retro-tool/retro-tool-client/pull/25
