### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by marciobarrios** [retro-tool/retro-tool#4]
To promote retro tool and to avoid creating useless retros every time we load the app.

**Comment by uesteibar** [comment]
One idea that was proposed in slack is to have something like:

```
234452 retros facilitated, with 1234515 posts and 64421 action items
```

with real numbers from the API, what do you think?

**Comment by marciobarrios** [comment]
I think it's awesome 😊

**Comment by marciobarrios** [comment]
Topics that IMO the landing should have:
- Some texts/screens to summarize what retrotool does (some nice values to promote: easy, free, real time and without authentication)
- A CTA to start a new retro (highlighting the feature of custom url and automatic retro number increase)
- Live statistics
- Some fun animations!

**Comment by uesteibar** [comment]
As discussed on slack, we will:

- Have the landing on `/`
- Move the automatic retro creation + redirection to `/new`

**Comment by uesteibar** [comment]
Do you think it would be useful to explain the stages of the retro in the landing? or at leas mention the lifetime of the retro, as in

```
add posts -> vote posts -> discuss -> add action items
```

**Comment by marciobarrios** [comment]
Sorry Unai I just read this, yes my plan is to briefly explain the different steps of a retro, I will propose something and then we can iterate together.
