### ISSUE TITLE
Hide the action items column until the 'Add action items' phase

### ISSUE THREAD

**Issue by uesteibar** [retro-tool/retro-tool#7]
The action items column is unnecessary until we reach the 'Add action items phase', so we can hide it until then.

**Comment by rudeayelo** [comment]
What if there're existing action items from the previous retro?

**Comment by uesteibar** [comment]
@rudeayelo should we maybe unify it with https://github.com/retro-tool/retro-tool/issues/8 into one single issue, and describe all the behaviour for this column in each phase?

**Comment by marciobarrios** [comment]
I wouldn't do this for now, could be confusing in my opinion.

**Comment by uesteibar** [comment]
I agree with @marciobarrios, let's close it for now and reopen it is we get feedback regarding this
